# Site settings
title: XMonsterh
header-img: "img/autumn2.jpg"
tagline: ""  
description: "Don't Think Too Much"  
baseurl: ""
url: "http://www.xnathanh.tech"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Nathan.h"
  email: xnathan.h@gmail.com
  bio: "don't think too much"

# Data
gavatar: https://image.winudf.com/1179/018041213cbd1cc7/icon=150x.png
favicon: img/n.png

#douban_username: -
#twitter_username: xnathanhs
facebook_username: xnathanh
github_username: xnathanh
#weibo_username: -  
#zhihu_username: -  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: US/Pacific-New

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nathan.h"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Nathan.h
  disqus :
      short_name : Nathan.h

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
